---
- name: Power on a VM on VMware ESXi Host
  gather_facts: false
  hosts: localhost
  connection: local
  vars_files:
    - vars/main.yaml

  tasks:
    - name: Power on virtual machine
      community.vmware.vmware_guest_powerstate:
        hostname: '{{ vcenter_host }}'
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        # name: "chmoreto_ISE-Ansible"
        name: "VMware-Ansible"
        state: powered-on

    
