---

#--------------------------------------------------------------------------
# This playbook will DELETE the VM from the ESXi host. The force command
# will delete a VM that is powered-on 
# 
#--------------------------------------------------------------------------

- name: Delete an ISE OVA on VMware ESXi Host
  gather_facts: false
  hosts: localhost
  connection: local
  vars_files:
    - vars/main.yaml

  tasks:
    - name: Delete ISE VM
      community.vmware.vmware_guest:
        validate_certs: no
        name: "VMware-Ansible" 
        # name: "chmoreto_ISE-Ansible" 
        state: absent
        force: yes
        

    
