---
# tasks file for ssh_key_local

- name: Validate Required Variables
  delegate_to: localhost
  loop:
    - ssh_key_directory
    - ssh_key_name
    - ssh_key_size
    - ssh_key_type
    - ssh_key_private_file
    - ssh_key_public_file
  when: lookup('vars', item) is undefined
  ansible.builtin.fail:
    fail_msg: ❌ Please set variable {{ item }}
#   register: results
# - ansible.builtin.debug: var=results

# ⚠ Python bcrypt module required on localhost to generate SSH keypair
- name: Install Python bcrypt Package
  delegate_to: localhost
  ansible.builtin.pip:
    name: bcrypt
    executable: pip3

- name: Local SSH Keypair Existence
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ ssh_key_directory }}/{{ ssh_key_name }}"
  register: keypair_stat

- name: Create SSH Keypair Passphrase
  when: not keypair_stat.stat.exists and ssh_key_passphrase is undefined
  block:
    - ansible.builtin.pause:
        prompt: Enter your SSH Keypair Passphrase
        echo: no
      register: input
    - ansible.builtin.set_fact:
        ssh_key_passphrase: "{{ input.user_input }}"

- name: Generate OpenSSH Keypair
  when: not keypair_stat.stat.exists
  delegate_to: localhost
  community.crypto.openssh_keypair:
    state: present
    type: "{{ ssh_key_type }}"
    comment: "{{ ssh_key_name }}"
    path: "{{ ssh_key_directory }}/{{ ssh_key_name }}"
    passphrase: "{{ ssh_key_passphrase }}"
    mode: 0600 # SSH key permissions
    size: "{{ ssh_key_size }}"
  register: keypair
# - ansible.builtin.debug: var=keypair

